version: '3'

services:

  srv:
    image: bfellows37/pasteapi:latest
    env_file:
      - ./deploy/srv.env
    links:
      - mongo

  app:
    image: bfellows37/paste:latest
    ports:
      - 80:4200
    env_file:
      - ./deploy/app.env
    links:
      - srv

  mongo:
    image: mongo:latest
    volumes:
      - ./deploy/data/db:/data/db
      - ./deploy/data/configdb:/data/configdb
